{
 "title": "Sample Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "dataset=\"$vt_dummy\" event < 42 | project _time=_time-rand(3600), total_requests=rand(10000)",
     "type": "adhoc"
    },
    {
     "query": "dataset=\"$vt_dummy\" event < 42 | project _time=_time-rand(3600), total_clients=rand(420)",
     "type": "adhoc"
    }
   ]
  },
  {
   "title": "Count by Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "dataset=\"cribl_internal_logs\" method=* | summarize by method",
     "type": "adhoc"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "dataset=\"$vt_dummy\" event < 42 | project _time=_time-rand(3600), latency= 42 + rand(4200)",
     "type": "adhoc"
    }
   ]
  },
  {
   "title": "Answer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "print 42", "type": "adhoc" }
   ]
  }
 ]
}