services:
  grafana:
    user: root
    container_name: 'criblcloud-search-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3333:3333/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/criblcloud-search-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/criblcloud-search-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.criblcloud-search-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: criblcloud-search-datasource
      GF_SERVER_HTTP_PORT: 3333
